# Tutorial pyOSRD #6
Creating custom agent

In [1]:
from pyosrd.agents.scheduler_agent import SchedulerAgent
import pandas as pd
from dataclasses import dataclass

## Creating a dummy agent
Create an agent that add 60 seconds of delay at the second zone the first train go throught.

In [2]:

class DummySchedulerAgent(SchedulerAgent):
    @property
    def steps_extra_delays(self) -> pd.DataFrame:
        """As an example, make train1 stop 60s more in second zone"""
        extra_delays = self.ref_schedule.durations * 0.
        extra_delays.iloc[0, 1] = 60.
        return extra_delays

## Test our agent on all scenarii
We can launch our custom agent on all scenarii implemented in the module OSRD.scenarii.

In [3]:
from pyosrd.agents.scheduler_agent import regulate_delays_with_agents

agent = DummySchedulerAgent("dummy")
regulate_delays_with_agents("all", agent)

[15:42:43,938] [INFO]  [StandaloneSimulationCommand] Loading infra: ./infra.json
[15:42:43,971] [INFO]              [FullInfra] parsing infra
[15:42:44,035] [INFO]              [FullInfra] adaptation to kotlin
[15:42:44,060] [INFO]              [FullInfra] loading signals
[15:42:44,067] [INFO]              [FullInfra] building blocks
[15:42:44,071] [INFO]  [StandaloneSimulationCommand] Loading input: ./simulation.json
[15:42:44,089] [INFO]  [StandaloneSimulationCommand] Running simulation for schedule group: group.0
[15:42:44,136] [DEBUG]             [Allowance] computing range n°1
[15:42:44,138] [DEBUG]             [Allowance]   computing section n°1
[15:42:44,139] [DEBUG]             [Allowance]   target time = 310.84094999999996
[15:42:44,139] [DEBUG]             [Allowance]     starting attempt 1
[15:42:44,140] [DEBUG]             [Allowance]     envelope time 518.958
[15:42:44,140] [DEBUG]             [Allowance]     starting attempt 2
[15:42:44,140] [DEBUG]             [Allowance]     envelope time 377.006
[15:42:44,140] [DEBUG]             [Allowance]     starting attempt 3
[15:42:44,141] [DEBUG]             [Allowance]     envelope time 331.565
[15:42:44,141] [DEBUG]             [Allowance]     starting attempt 4
[15:42:44,141] [DEBUG]             [Allowance]     envelope time 312.766
[15:42:44,143] [INFO]  [StandaloneSimulationCommand] Running simulation for schedule group: group.1
[15:42:44,149] [DEBUG]             [Allowance] computing range n°1
[15:42:44,149] [DEBUG]             [Allowance]   computing section n°1
[15:42:44,149] [DEBUG]             [Allowance]   target time = 310.84094999999996
[15:42:44,149] [DEBUG]             [Allowance]     starting attempt 1
[15:42:44,149] [DEBUG]             [Allowance]     envelope time 518.958
[15:42:44,149] [DEBUG]             [Allowance]     starting attempt 2
[15:42:44,149] [DEBUG]             [Allowance]     envelope time 377.006
[15:42:44,149] [DEBUG]             [Allowance]     starting attempt 3
[15:42:44,150] [DEBUG]             [Allowance]     envelope time 331.565
[15:42:44,150] [DEBUG]             [Allowance]     starting attempt 4
[15:42:44,150] [DEBUG]             [Allowance]     envelope time 312.766
[15:42:44,151] [INFO]  [StandaloneSimulationCommand] All simulations completed
[15:42:44,151] [INFO]  [StandaloneSimulationCommand] Saving results at: ./results.json

                         dummy
c1_2trains_delay_train1  360.0

## Compare two agents

The function regulate_scenarii_with_agents can be launched on multiple agents at the same time. It returns a pandas DataFrame containing the ponderated delays
for all scenarii.

An agent can be compared to another one using those scenarii.

In [4]:

class DumberSchedulerAgent(SchedulerAgent):
    @property
    def steps_extra_delays(self) -> pd.DataFrame:
        """As an example, make train1 stop 120s more in second zone"""
        extra_delays = self.ref_schedule.durations * 0.
        extra_delays.iloc[0, 1] = 120.
        return extra_delays

To speed up the notebook execution the next call is done only on one scenario "c1_delay".

In [7]:

agent_dumber = DumberSchedulerAgent("dumber")
regulate_delays_with_agents("c1_2trains_delay_train1", [agent, agent_dumber])

[15:43:05,787] [INFO]  [StandaloneSimulationCommand] Loading infra: ./infra.json
[15:43:05,821] [INFO]              [FullInfra] parsing infra
[15:43:05,888] [INFO]              [FullInfra] adaptation to kotlin
[15:43:05,910] [INFO]              [FullInfra] loading signals
[15:43:05,916] [INFO]              [FullInfra] building blocks
[15:43:05,920] [INFO]  [StandaloneSimulationCommand] Loading input: ./simulation.json
[15:43:05,934] [INFO]  [StandaloneSimulationCommand] Running simulation for schedule group: group.2
[15:43:05,982] [DEBUG]             [Allowance] computing range n°1
[15:43:05,983] [DEBUG]             [Allowance]   computing section n°1
[15:43:05,984] [DEBUG]             [Allowance]   target time = 310.84094999999996
[15:43:05,984] [DEBUG]             [Allowance]     starting attempt 1
[15:43:05,985] [DEBUG]             [Allowance]     envelope time 518.958
[15:43:05,985] [DEBUG]             [Allowance]     starting attempt 2
[15:43:05,985] [DEBUG]             [Allowance]     envelope time 377.006
[15:43:05,985] [DEBUG]             [Allowance]     starting attempt 3
[15:43:05,985] [DEBUG]             [Allowance]     envelope time 331.565
[15:43:05,985] [DEBUG]             [Allowance]     starting attempt 4
[15:43:05,985] [DEBUG]             [Allowance]     envelope time 312.766
[15:43:05,987] [INFO]  [StandaloneSimulationCommand] Running simulation for schedule group: group.3
[15:43:05,991] [DEBUG]             [Allowance] computing range n°1
[15:43:05,991] [DEBUG]             [Allowance]   computing section n°1
[15:43:05,991] [DEBUG]             [Allowance]   target time = 310.84094999999996
[15:43:05,991] [DEBUG]             [Allowance]     starting attempt 1
[15:43:05,991] [DEBUG]             [Allowance]     envelope time 518.958
[15:43:05,991] [DEBUG]             [Allowance]     starting attempt 2
[15:43:05,991] [DEBUG]             [Allowance]     envelope time 377.006
[15:43:05,991] [DEBUG]             [Allowance]     starting attempt 3
[15:43:05,991] [DEBUG]             [Allowance]     envelope time 331.565
[15:43:05,992] [DEBUG]             [Allowance]     starting attempt 4
[15:43:05,992] [DEBUG]             [Allowance]     envelope time 312.766
[15:43:05,994] [INFO]  [StandaloneSimulationCommand] All simulations completed
[15:43:05,994] [INFO]  [StandaloneSimulationCommand] Saving results at: ./results.json
[15:43:06,322] [INFO]  [StandaloneSimulationCommand] Loading infra: ./infra.json
[15:43:06,350] [INFO]              [FullInfra] parsing infra
[15:43:06,407] [INFO]              [FullInfra] adaptation to kotlin
[15:43:06,429] [INFO]              [FullInfra] loading signals
[15:43:06,434] [INFO]              [FullInfra] building blocks
[15:43:06,438] [INFO]  [StandaloneSimulationCommand] Loading input: ./simulation.json
[15:43:06,450] [INFO]  [StandaloneSimulationCommand] Running simulation for schedule group: group.4
[15:43:06,493] [DEBUG]             [Allowance] computing range n°1
[15:43:06,495] [DEBUG]             [Allowance]   computing section n°1
[15:43:06,496] [DEBUG]             [Allowance]   target time = 310.84094999999996
[15:43:06,496] [DEBUG]             [Allowance]     starting attempt 1
[15:43:06,497] [DEBUG]             [Allowance]     envelope time 518.958
[15:43:06,497] [DEBUG]             [Allowance]     starting attempt 2
[15:43:06,497] [DEBUG]             [Allowance]     envelope time 377.006
[15:43:06,497] [DEBUG]             [Allowance]     starting attempt 3
[15:43:06,498] [DEBUG]             [Allowance]     envelope time 331.565
[15:43:06,498] [DEBUG]             [Allowance]     starting attempt 4
[15:43:06,498] [DEBUG]             [Allowance]     envelope time 312.766
[15:43:06,500] [INFO]  [StandaloneSimulationCommand] Running simulation for schedule group: group.5
[15:43:06,504] [DEBUG]             [Allowance] computing range n°1
[15:43:06,504] [DEBUG]             [Allowance]   computing section n°1
[15:43:06,504] [DEBUG]             [Allowance]   target time = 310.84094999999996
[15:43:06,505] [DEBUG]             [Allowance]     starting attempt 1
[15:43:06,505] [DEBUG]             [Allowance]     envelope time 518.958
[15:43:06,505] [DEBUG]             [Allowance]     starting attempt 2
[15:43:06,505] [DEBUG]             [Allowance]     envelope time 377.006
[15:43:06,505] [DEBUG]             [Allowance]     starting attempt 3
[15:43:06,505] [DEBUG]             [Allowance]     envelope time 331.565
[15:43:06,505] [DEBUG]             [Allowance]     starting attempt 4
[15:43:06,505] [DEBUG]             [Allowance]     envelope time 312.766
[15:43:06,507] [INFO]  [StandaloneSimulationCommand] All simulations completed
[15:43:06,507] [INFO]  [StandaloneSimulationCommand] Saving results at: ./results.json

                         dummy  dumber
c1_2trains_delay_train1  360.0   480.0